-- This file has been generated by Dungeon Editor 2.2.4

--- level 1 ---

newMap{
	name = "Unnamed",
	width = 32,
	height = 32,
	levelCoord = {0,0,0},
	ambientTrack = "dungeon",
	tiles = {
		"dungeon_floor",
		"dungeon_wall",
	}
}

loadLayer("tiles", {
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
})

spawn("starting_location",16,15,1,0,"starting_location")
spawn("torch_holder",15,14,0,0,"torch_holder_1")
torch_holder_1.controller:setHasTorch(true)
spawn("script_entity",4,5,1,0,"champions")
champions.script:loadFile("mod_assets/jkos/champions.lua")
spawn("wall_button",16,15,1,0,"wall_button_1")
wall_button_1.button:setDisableSelf(false)
wall_button_1.button:addConnector("onActivate", "champion_recruit_1", "enable")
spawn("champion_recruit",18,15,3,0,"champion_recruit_1")
champion_recruit_1.script:setSource("--DON'T MODIFY THESE METHODS(unless you know what you are doing)\
championDefs = {}\
\
function defineChampion(def)\
\9self.championDefs[def.name] = def\
end\
-- Call this function to show the gui\
function enable()\
\9champions.script.setStore(self.go.id)\
\9if champions.script.hasChampions() then\
\9\9champions.script.showGui(true)\
\9end\
end\
\
-- ADD YOUR CHAMPION DEFINITIONS HERE\
-- This is just a template, you can modify it as you like and add more champions\
defineChampion{\
      name = 'Lab Rat',\
      race = 'ratling',\
      class = 'farmer',\
      sex='male',\
      portrait='assets/textures/portraits/ratling_male_02.tga',\
      experience=6000,\
      baseStats = {\
         strength=20,\
         dexterity=13,\
         vitality=18,\
         willpower=15\
      },\
      skillLevels = {\
         accuracy=1,\
         light_weapons=4\
      },\
      energy=110,\
      food=1000,\
      health=100,\
      level=4,\
      skillPoints=0,\
      traits={\
         ratling=true,\
\9\9 farmer=true,\
\9\9 quick=true,\
\9\9 mutation=true\
      },\
\9  description = \"This is the decription of the champion, just testing how much text can be typed here.\"\
\9\9\9..\"This is the decription of the champion, just testing how much text can be typed here.\"\
\9\9\9..\"This is the decription of the champion, just testing how much text can be typed here.\"\
   }\
\
defineChampion{\
      name = 'Test Woman',\
      race = 'human',\
      class = 'fighter',\
      sex='female',\
      portrait='assets/textures/portraits/human_female_04.tga',\
      experience=6000,\
      baseStats = {\
         strength=12,\
         dexterity=12,\
         vitality=18,\
         willpower=10\
      },\
      skillLevels = {\
         accuracy=1,\
         light_weapons=4\
      },\
      energy=110,\
      food=1000,\
      health=100,\
      level=4,\
      skillPoints=0,\
      traits={\
         human=true,\
      },\
\9  items={\
\9     'dagger',\
\9     'bear_pelt',\
\9\9 'archmage_hat',\
\9\9 'archmage_loafers',\
\9\9 'archmage_mantle',\
         'potion_healing',\
\9  },\
\9  description = \"Added champion description and support for items. When you recruit the champion, his/hers items will be spawned in a wooden box which is then set as the mouseItem\"\
   }\
\
defineChampion{\
      name = 'Minotaur With really long name',\
      race = 'minotaur',\
      class = 'barbarian',\
      sex='male',\
      portrait='assets/textures/portraits/minotaur_male_02.tga',\
      experience=11000,\
      baseStats = {\
         strength=25,\
         dexterity=10,\
         vitality=20,\
         willpower=10\
      },\
      skillLevels = {\
         accuracy=1,\
         light_weapons=4,\
\9\9 armors=4\
      },\
      energy=110,\
      food=1000,\
      health=100,\
      level=5,\
      skillPoints=0,\
      traits={\
         human=true,\
      },\
\9  items={\
\9     'ax',\
\9     'potion_healing',\
\9     'bane'\
\9  },\
\9  onDrawStats = function(self,g)\
\9\9--you can draw your own stuff here\
\9  end,\
\9  onRecruit = function(self)\
\9\9\9hudPrint('This will be printed when champion is recruited')\
\9  end\
   }\
")
spawn("champion_recruit",12,15,1,0,"champion_recruit_2")
champion_recruit_2.script:setSource("--DON'T MODIFY THESE METHODS(unless you know what you are doing)\
championDefs = {}\
\
function defineChampion(def)\
\9self.championDefs[def.name] = def\
end\
-- Call this function to show the gui\
function enable()\
\9champions.script.setStore(self.go.id)\
\9if champions.script.hasChampions() then\
\9\9champions.script.showGui(true)\
\9end\
end\9\
\
-- ADD YOUR CHAMPION DEFINITIONS HERE\
-- This is just a template, you can modify it as you like and add more champions\
defineChampion{\
      name = 'Champion Template',\
      race = 'ratling',\
      class = 'farmer',\
      sex='male',\
      portrait='assets/textures/portraits/ratling_male_02.tga',\
      experience=6000,\
      baseStats = {\
         strength=20,\
         dexterity=13,\
         vitality=18,\
         willpower=15\
      },\
      skillLevels = {\
         accuracy=1,\
         light_weapons=4\
      },\
      energy=110,\
      food=1000,\
      health=100,\
      level=4,\
      skillPoints=0,\
      traits={\
         agile=true,\
      },\
\9  description = \"Decription of the champion\"\
   }\
")
spawn("champion_recruit",15,18,2,0,"champion_recruit_3")
champion_recruit_3.script:setSource("--DON'T MODIFY THESE METHODS(unless you know what you are doing)\
championDefs = {}\
\
function defineChampion(def)\
\9self.championDefs[def.name] = def\
end\
-- Call this function to show the gui\
function enable()\
\9champions.script.setStore(self.go.id)\
\9if champions.script.hasChampions() then\
\9\9champions.script.showGui(true)\
\9end\
end\
\
-- ADD YOUR CHAMPION DEFINITIONS HERE\
-- This is just a template, you can modify it as you like and add more champions\
defineChampion{\
      name = 'Zalkragasdf',\
      race = 'insectoid',\
      class = 'fighter',\
      sex='male',\
      portrait='assets/textures/portraits/insectoid_male_02.tga',\
      experience=6000,\
      baseStats = {\
         strength=20,\
         dexterity=13,\
         vitality=18,\
         willpower=15\
      },\
      skillLevels = {\
         accuracy=1,\
         light_weapons=4\
      },\
      energy=110,\
      food=1000,\
      health=100,\
      level=4,\
      skillPoints=0,\
      traits={\
         agile=true,\
      },\
\9  description = \"Decription of the champion\",\
\9  items={\
\9     'dagger',\
         'potion_healing',\
\9  },\
   }\
defineChampion{\
      name = 'Champion Name',\
      race = 'ratling',\
      class = 'farmer',\
      sex='male',\
      portrait='assets/textures/portraits/ratling_male_02.tga',\
      experience=6000,\
      baseStats = {\
         strength=20,\
         dexterity=13,\
         vitality=18,\
         willpower=15\
      },\
      skillLevels = {\
         accuracy=1,\
         light_weapons=4\
      },\
      energy=110,\
      food=1000,\
      health=100,\
      level=4,\
      skillPoints=0,\
      traits={\
         agile=true,\
      },\
\9  description = \"Decription of the champion\",\
\9  items={\
\9     'dagger',\
         'potion_healing',\
\9  },\
   }\
")
spawn("pullchain",15,16,2,0,"pullchain_1")
pullchain_1.button:setDisableSelf(false)
pullchain_1.button:addConnector("onActivate", "champion_recruit_3", "enable")
spawn("dungeon_pressure_plate",14,15,2,0,"dungeon_pressure_plate_1")
dungeon_pressure_plate_1.floortrigger:setTriggeredByParty(true)
dungeon_pressure_plate_1.floortrigger:setTriggeredByMonster(false)
dungeon_pressure_plate_1.floortrigger:setTriggeredByItem(false)
dungeon_pressure_plate_1.floortrigger:setTriggeredByDigging(false)
dungeon_pressure_plate_1.floortrigger:setDisableSelf(false)
dungeon_pressure_plate_1.floortrigger:addConnector("onActivate", "champion_recruit_2", "enable")
spawn("dungeon_door_portcullis",14,17,0,0,"dungeon_door_portcullis_3")
spawn("dungeon_door_portcullis",15,17,0,0,"dungeon_door_portcullis_4")
spawn("dungeon_door_portcullis",16,17,0,0,"dungeon_door_portcullis_5")
spawn("herder",14,17,1,0,"herder_1")
spawn("script_entity",31,0,0,0,"guiItemBrowser")
guiItemBrowser.script:setSource("    -- commented out non working guiItems\
    items = {\
    \"AbilityMinusDown\",\
    \"AbilityMinusHover\",\
    \"AbilityMinusUp\",\
    \"AbilityPlusDown\",\
    \"AbilityPlusHover\",\
    \"AbilityPlusUp\",\
    \"AccuracySymbol\",\
    \"AttackFrame\",\
    \"AttackFrameBarBackground\",\
    \"AttackFrameBarBackgroundShort\",\
    \"AttackFrameConditionRect\",\
    \"AttackFrameDisabled\",\
    \"AttackFrameEnergy\",\
    \"AttackFrameEnergyShort\",\
    \"AttackFrameHealthGreen\",\
    \"AttackFrameHealthGreenShort\",\
    \"AttackFrameHealthRed\",\
    \"AttackFrameHealthRedShort\",\
    \"AttackFrameHealthYellow\",\
    \"AttackFrameHealthYellowShort\",\
    --\"AttackFrameItemSlot\",\
    --\"AttackFramePortraitRect\",\
    --\"AttackFrameSelected1\",\
    \"AttackFrameSelected2\",\
    \"AttackFrameShield\",\
    --\"AttackFrameSlotSpacing\",\
    --\"AttackFrameSpacing\",\
    \"AttackPowerSymbol\",\
    --\"Background\",\
    \"ButtonAccept\",\
    \"ButtonAcceptDisabled\",\
    \"ButtonAcceptHover\",\
    \"ButtonApply\",\
    \"ButtonApplyHover\",\
    \"ButtonCancel\",\
    \"ButtonCancelHover\",\
    \"ButtonChoose\",\
    \"ButtonChooseDisabled\",\
    \"ButtonChooseHover\",\
    \"ButtonClear\",\
    \"ButtonClearDisabled\",\
    \"ButtonClearHover\",\
    \"ButtonClose\",\
    \"ButtonCloseHover\",\
    \"ButtonDefaults\",\
    \"ButtonDefaultsHover\",\
    \"ButtonImport\",\
    \"ButtonImportDisabled\",\
    \"ButtonImportHover\",\
    \"ButtonKeyConfig\",\
    \"ButtonKeyConfigHover\",\
    \"ButtonNo\",\
    \"ButtonNoHover\",\
    \"ButtonSave\",\
    \"ButtonSaveHover\",\
    \"ButtonYes\",\
    \"ButtonYesHover\",\
    \"ChampionConditionOverlay\",\
    \"CharGenBackToMenu\",\
    \"CharGenBackToMenuHover\",\
    \"CharGenNameBox\",\
    \"CharGenPortraitSel128\",\
    \"CharGenPortraitSelBig\",\
    \"CharGenPortraitSelSmall\",\
    \"CharGenSkillMinusHover\",\
    \"CharGenSkillMinusImage\",\
    \"CharGenSkillPlusHover\",\
    \"CharGenSkillPlusImage\",\
    \"CharGenSkillSlot\",\
    \"CharGenSkillSlotHover\",\
    \"CharGenStartGame\",\
    \"CharGenStartGameDisabled\",\
    \"CharGenStartGameHover\",\
    \"CharSheet\",\
    \"CheckBox\",\
    \"CheckBoxChecked\",\
    \"CheckBoxCheckedHover\",\
    \"CheckBoxHover\",\
    \"ChooseDungeonBackground\",\
    \"ChooseDungeonDownload\",\
    \"ChooseDungeonDownloadHvr\",\
    \"ChooseDungeonUnsubscribe\",\
    \"ChooseDungeonUnsubscribeHvr\",\
    \"ChooseDungeonWorkshop\",\
    \"ChooseDungeonWorkshopHvr\",\
    \"ChoosePortraitDialog\",\
    \"CloseButtonHover\",\
    \"ComboBox\",\
    \"ComboBoxHover\",\
    \"ConfirmDialog\",\
    \"ContainerChest\",\
    \"ContainerSack\",\
    \"CraftPotionPanel\",\
    \"DamageSplash\",\
    \"DialogFrameCornerBottomLeft\",\
    \"DialogFrameCornerBottomRight\",\
    \"DialogFrameCornerTopLeft\",\
    \"DialogFrameCornerTopRight\",\
    \"DialogFrameSideBottom\",\
    \"DialogFrameSideLeft\",\
    \"DialogFrameSideRight\",\
    \"DialogFrameSideTop\",\
    \"DialogShadowCornerBottomLeft\",\
    \"DialogShadowCornerBottomRight\",\
    \"DialogShadowCornerTopLeft\",\
    \"DialogShadowCornerTopRight\",\
    \"DialogShadowSideBottom\",\
    \"DialogShadowSideLeft\",\
    \"DialogShadowSideRight\",\
    \"DialogShadowSideTop\",\
    \"EnterTextDialog\",\
    \"EquipmentSlots\",\
    \"ExpBar\",\
    \"ExpBarFrame\",\
    \"FoodBarFrame\",\
    \"FoodBarGreen\",\
    \"FoodBarRed\",\
    \"FoodBarYellow\",\
    \"GameOver\",\
    \"HandSlot1\",\
    \"HandSlot2\",\
    \"HandSlotHighlight1\",\
    \"HandSlotHighlight2\",\
    \"HitSplash\",\
    \"HitSplashLarge\",\
    \"HitSplashSmall\",\
    \"Injury\",\
    \"InjuryHand1\",\
    \"InjuryHand2\",\
    \"InjurySmall\",\
    \"InstructionsAttackPanel\",\
    \"InventoryTab\",\
    \"IslandMasterSymbol\",\
    \"KeyBindings\",\
    \"MapArrowLeft\",\
    \"MapArrowRight\",\
    \"MapButtonHover\",\
    \"MapClose\",\
    \"MapToolsBackground\",\
    \"MapToolsCenter\",\
    \"MapToolsCenterHover\",\
    \"MapToolsClose\",\
    \"MapToolsCloseHover\",\
    \"MapToolsCross\",\
    \"MapToolsCrossHover\",\
    \"MapToolsExclamation\",\
    \"MapToolsExclamationHover\",\
    \"MapToolsLevelDivider\",\
    \"MapToolsLevelDown\",\
    \"MapToolsLevelDownHover\",\
    \"MapToolsLevelUp\",\
    \"MapToolsLevelUpHover\",\
    \"MapToolsQuestion\",\
    \"MapToolsQuestionHover\",\
    \"MapToolsQuil\",\
    \"MapToolsQuilHover\",\
    \"MenuButtonHover\",\
    \"Moon\",\
    \"MovementArrowDown\",\
    \"MovementArrows\",\
    \"NewGame\",\
    \"NextChampionHover\",\
    \"PackSlotBgImage\",\
    \"PreviousChampionHover\",\
    \"QuickSwapButtonDown1\",\
    \"QuickSwapButtonDown2\",\
    \"QuickSwapButtonUp1\",\
    \"QuickSwapButtonUp2\",\
    \"RandomizeButton\",\
    \"RandomizeButtonHover\",\
    \"SaveGameBackground\",\
    \"SaveGameDeleteButton\",\
    \"SaveGameDeleteHover\",\
    \"SaveGamePortraitFrame\",\
    \"SaveGameSlot\",\
    \"SaveGameSlotHover\",\
    \"SaveGameTitleLoad\",\
    \"SaveGameTitleSave\",\
    \"Settings\",\
    \"SkillMinusImage\",\
    \"SkillPlusHover\",\
    \"SkillPlusImage\",\
    \"SkillSlots\",\
    \"SkillSlotsHighlight\",\
    \"SkillTick\",\
    \"SkillTickUpgrade\",\
    \"SkillTickUpgradeSelected\",\
    \"SkillsTab\",\
    \"SkillsTabHighlight\",\
    \"SkillsTabHighlightSel\",\
    \"SleepButtonHover\",\
    \"Slider\",\
    \"SliderKnob\",\
    \"SliderKnobHover\",\
    \"SmallFoodBarFrame\",\
    \"SmallFoodBarGreen\",\
    \"SmallFoodBarRed\",\
    \"SmallFoodBarYellow\",\
    \"SpellFizzle\",\
    \"SpellNoEnergy\",\
    \"SpellPanel\",\
    \"SpellPanelNoButtons\",\
    \"SpellRuneGlow\",\
    \"SpellRunes\",\
    \"SpellRunesGlow\",\
    \"Star\",\
    \"StatisticsDialog\",\
    \"StatsTab\",\
    \"Sun\",\
    \"TextButton\",\
    \"TextButtonHover\",\
    \"TextButtonLong\",\
    \"TextButtonLongHover\",\
    \"TraitSlot\",\
    \"TraitSlotHover\",\
    \"TraitSlotLong\",\
    \"TraitSlotLongHover\",\
    \"TraitsTab\",\
    \"UnarmedAttackBearLeft\",\
    \"UnarmedAttackBearRight\",\
    \"UnarmedAttackLeft\",\
    \"UnarmedAttackMageLeft\",\
    \"UnarmedAttackMageRight\",\
    \"UnarmedAttackRight\"\
    }\
\
\
    i = 1\
\
    function showItem(item)\
       if type(item) == 'number' then\
          i = item\
          return nil\
       end\
       \
       for j=1,#items do\
          if items[j] == item then\
             i = j\
             return nil\
          end\
       end\
    end\
\
    function next()\
       i = i + 1\
    end\
\
    function prev()\
       i = i - 1\
    end\
\
    keyPressed = false\
\
    function drawItem(party,g)\
\
       g.drawText('Prev (,)',10,240)\
       if g.button('Prev',10,230,50,20) or g.keyDown(',') and not keyPressed then\
          prev()\
       end\
       \
       g.drawText('Next (.)',70,240)\
       if g.button('Next',70,230,50,20) or g.keyDown('.') and not keyPressed then\
          next()\
       end\
\
       if g.keyDown(',') or g.keyDown('.') then\
          keyPressed = true\
       else\
          keyPressed = false\
       end   \
       \
       if i<1 then i = #items end\
       if i>#items then i = 1 end\
       local item = items[i]   \
       g.drawGuiItem(item, 10, 270)   \
       g.drawText(item,10, 260)\
\
    end\
\
    function enable()\
       party.party:addConnector('onDrawGui',self.go.id,'drawItem')\
    end\
    function disable()\
       party.party:removeConnector('onDrawGui',self.go.id,'drawItem')\
    end\
\
   -- enable()\
")
