-- This file has been generated by Dungeon Editor 2.1.17

--- level 1 ---

newMap{
	name = "Unnamed",
	width = 32,
	height = 32,
	levelCoord = {0,0,0},
	ambientTrack = "dungeon",
	tiles = {
		"dungeon_floor",
		"dungeon_wall",
	}
}

loadLayer("tiles", {
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
})

spawn("starting_location",16,15,1,0,"starting_location")
spawn("torch_holder",15,14,0,0,"torch_holder_1")
torch_holder_1.controller:setHasTorch(true)
spawn("script_entity",4,5,1,0,"champions")
champions.script:loadFile("mod_assets/jkos/champions.lua")
spawn("wall_button",16,15,1,0,"wall_button_1")
wall_button_1.button:setDisableSelf(false)
wall_button_1.button:addConnector("onActivate", "script_entity_1", "recruit")
spawn("script_entity",18,15,3,0,"script_entity_1")
script_entity_1.script:setSource("\
function recruit()\
\9champions.script.showGui(true)\
end\
function closeGui()\
\9champions.script.showGui(false)\
end\
\
function defineChampions()\
   champions.script.defineChampion{\
      name = 'Lab Rat',\
      race = 'ratling',\
      class = 'farmer',\
      sex='male',\
      portrait='assets/textures/portraits/ratling_male_02.tga',\
      experience=6000,\
      baseStats = {\
         strength=20,\
         dexterity=13,\
         vitality=18,\
         willpower=15\
      },\
      skillLevels = {\
         accuracy=1,\
         light_weapons=4\
      },\
      energy=110,\
      food=1000,\
      health=100,\
      level=4,\
      skillPoints=0,\
      traits={\
         human=true,\
      },\
\9  description = \"This is the decription of the champion, just testing how much text can be typed here.\"\
\9\9\9..\"This is the decription of the champion, just testing how much text can be typed here.\"\
\9\9\9..\"This is the decription of the champion, just testing how much text can be typed here.\"\
   }\
\
   champions.script.defineChampion{\
      name = 'Test Woman',\
      race = 'human',\
      class = 'fighter',\
      sex='female',\
      portrait='assets/textures/portraits/human_female_04.tga',\
      experience=6000,\
      baseStats = {\
         strength=12,\
         dexterity=12,\
         vitality=18,\
         willpower=10\
      },\
      skillLevels = {\
         accuracy=1,\
         light_weapons=4\
      },\
      energy=110,\
      food=1000,\
      health=100,\
      level=4,\
      skillPoints=0,\
      traits={\
         human=true,\
      },\
\9  items={\
\9     'dagger',\
\9     'potion_healing',\
\9     'bear_pelt',\
\9\9 'archmage_hat',\
\9\9 'archmage_loafers',\
\9\9 'archmage_mantle'\
\9  },\
\9  description = \"Added champion description and support for items. When you recruit the champion, his/her's items will be spawned in a wooden box which is then set as the mouseItem\"\
   }\
   champions.script.defineChampion{\
      name = 'Minotaur With really long name',\
      race = 'minotaur',\
      class = 'barbarian',\
      sex='male',\
      portrait='assets/textures/portraits/minotaur_male_02.tga',\
      experience=11000,\
      baseStats = {\
         strength=25,\
         dexterity=10,\
         vitality=20,\
         willpower=10\
      },\
      skillLevels = {\
         accuracy=1,\
         light_weapons=4,\
\9\9 armors=4\
      },\
      energy=110,\
      food=1000,\
      health=100,\
      level=5,\
      skillPoints=0,\
      traits={\
         human=true,\
      },\
\9  items={\
\9     'ax',\
\9     'potion_healing',\
\9     'bane'\
\9  },\
\9  onDrawStats = function(self,g)\
\9\9--you can draw your own stuff here\
\9  end,\
\9  onRecruit = function(self)\
\9\9\9hudPrint('This will be printed when champion is recruited')\
\9  end\
   }\
\
\9\
end\
defineChampions()")
spawn("floor_trigger",16,15,1,0,"floor_trigger_1")
floor_trigger_1.floortrigger:setTriggeredByParty(true)
floor_trigger_1.floortrigger:setTriggeredByMonster(false)
floor_trigger_1.floortrigger:setTriggeredByItem(false)
floor_trigger_1.floortrigger:setTriggeredByDigging(false)
floor_trigger_1.floortrigger:setDisableSelf(false)
floor_trigger_1.floortrigger:addConnector("onDeactivate", "script_entity_1", "closeGui")
