-- This file has been generated by Dungeon Editor 2.1.17

--- level 1 ---

newMap{
	name = "Unnamed",
	width = 32,
	height = 32,
	levelCoord = {0,0,0},
	ambientTrack = "dungeon",
	tiles = {
		"dungeon_floor",
		"dungeon_wall",
	}
}

loadLayer("tiles", {
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
	2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
})

spawn("starting_location",16,15,1,0,"starting_location")
spawn("torch_holder",15,14,0,0,"torch_holder_1")
torch_holder_1.controller:setHasTorch(true)
spawn("script_entity",4,5,1,0,"champions")
champions.script:loadFile("mod_assets/jkos/champions.lua")
spawn("wall_button",16,15,1,0,"wall_button_1")
wall_button_1.button:setDisableSelf(false)
wall_button_1.button:addConnector("onActivate", "script_entity_1", "recruit")
spawn("script_entity",18,15,3,0,"script_entity_1")
script_entity_1.script:setSource("\
function recruit()\
\9champions.script.showGui(true)\
end\
\
function defineChampions()\
\
   champions.script.defineChampion{\
      name = 'Lab Rat',\
      race = 'ratling',\
      class = 'farmer',\
      sex='male',\
      portrait='assets/textures/portraits/ratling_male_02.tga',\
      experience=6000,\
      baseStats = {\
         strength=20,\
         dexterity=13,\
         vitality=18,\
         willpower=15\
      },\
      skillLevels = {\
         accuracy=1,\
         light_weapons=4\
      },\
      energy=110,\
      food=1000,\
      health=100,\
      level=4,\
      skillPoints=0,\
      traits={\
         human=true,\
      }\
   }\
\
   champions.script.defineChampion{\
      name = 'Test Woman',\
      race = 'human',\
      class = 'fighter',\
      sex='female',\
      portrait='assets/textures/portraits/human_female_04.tga',\
      experience=6000,\
      baseStats = {\
         strength=12,\
         dexterity=12,\
         vitality=18,\
         willpower=10\
      },\
      skillLevels = {\
         accuracy=1,\
         light_weapons=4\
      },\
      energy=110,\
      food=1000,\
      health=100,\
      level=4,\
      skillPoints=0,\
      traits={\
         human=true,\
      }\
   }\
   champions.script.defineChampion{\
      name = 'Minotaur With really long name',\
      race = 'minotaur',\
      class = 'barbarian',\
      sex='male',\
      portrait='assets/textures/portraits/minotaur_male_02.tga',\
      experience=6000,\
      baseStats = {\
         strength=25,\
         dexterity=10,\
         vitality=20,\
         willpower=10\
      },\
      skillLevels = {\
         accuracy=1,\
         light_weapons=4\
      },\
      energy=110,\
      food=1000,\
      health=100,\
      level=4,\
      skillPoints=0,\
      traits={\
         human=true,\
      }\
   }\
\
\9\
end\
defineChampions()")
spawn("script_entity",6,5,2,0,"jkos_gui")
jkos_gui.script:loadFile("mod_assets/jkos/gui.lua")
